### ISSUE TITLE
수식 깨짐 현상

### ISSUE THREAD

**Issue by Zeta611** [Axect/hugo_blog#1]
안녕하세요, 제 웹 브라우저에서 블로그를 보면 다음과 같이 수식이 깨집니다.
혹시 제 브라우저 (혹은 폰트) 문제일까요?

<img width="765" alt="Screenshot 2024-05-21 at 22 45 20" src="https://github.com/Axect/hugo_blog/assets/9553691/64a7bbef-58a8-4c51-9516-82d38fe95ed7">

**Comment by Axect** [comment]
안녕하세요. 일단 제가 쓰는 브라우저들 (파이어폭스, 엣지, 크롬) 에서는 PC와 모바일 환경 모두에서 다음과 같이 정상적으로 보이는걸 확인하였습니다. 

![Screenshot_20240521_230639_Edge.png](https://github.com/Axect/hugo_blog/assets/17744450/e2084c65-4a50-4f60-a102-3c9c31dd42b4)

혹시 다음 처럼 수식 부분을 눌러 MathJax에서의 렌더링을 SVG로 바꿔보시면 어떨까요?

![Screenshot_20240521_230946_Edge.png](https://github.com/Axect/hugo_blog/assets/17744450/ed227b7b-ac2f-42fe-9d42-adb1ff9026d3)

**Comment by Zeta611** [comment]
기본으로 HTML-CSS로 되어 있었는데요, SVG로 선택하니 잘 표시됩니다. 감사합니다 :)

참고로 제 환경은
macOS 14.5 (23F79)
Arc browser version 1.43.0 (50018)
Chromium Engine Version 125.0.6422.60
입니다.

**Comment by Axect** [comment]
제가 MacOS 환경에서의 브라우저들에서는 테스트를 해보지 못하여 렌더링 문제가 있는지 몰랐었네요. MathJax 렌더링 기본 설정을 바꿀 수 있는지 한번 찾아보겠습니다.
알려주셔서 감사합니다~!
